In [67]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [68]:
df_train = pd.read_csv('train.csv')
df_train.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,Gray,None reported,Yes,4200
1,1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,Beige,At least 1 accident or damage reported,Yes,4999
2,2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,Gray,None reported,Yes,13900
3,3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,Black,None reported,Yes,45000
4,4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,Beige,None reported,Yes,97500

In [69]:
df_train.isnull().sum()

id                  0
brand               0
model               0
model_year          0
milage              0
fuel_type        5083
engine              0
transmission        0
ext_col             0
int_col             0
accident         2452
clean_title     21419
price               0
dtype: int64

In [70]:
df_test = pd.read_csv('test.csv')
df_test.head()

,id,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title
0,188533,Land,Rover LR2 Base,2015,98000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,Beige,None reported,Yes
1,188534,Land,Rover Defender SE,2020,9142,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Silver,Black,None reported,Yes
2,188535,Ford,Expedition Limited,2022,28121,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,White,Ebony,None reported,NaN
3,188536,Audi,A6 2.0T Sport,2016,61258,Gasoline,2.0 Liter TFSI,Automatic,Silician Yellow,Black,None reported,NaN
4,188537,Audi,A6 2.0T Premium Plus,2018,59000,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,Black,None reported,Yes

In [71]:
df_test.isnull().sum()

id                  0
brand               0
model               0
model_year          0
milage              0
fuel_type        3383
engine              0
transmission        0
ext_col             0
int_col             0
accident         1632
clean_title     14239
dtype: int64

In [72]:
test_ids = df_test['id']

In [73]:
print(f"Shape del train: {df_train.shape}\n")
print(f"Shape del test: {df_test.shape}")

Shape del train: (188533, 13)

Shape del test: (125690, 12)

In [74]:
print("=====================Train=====================\n")
print(df_train.info())
print("\n=====================Test======================\n")
print(df_test.info())

=====================Train=====================

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188533 entries, 0 to 188532
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            188533 non-null  int64
 1   brand         188533 non-null  object
 2   model         188533 non-null  object
 3   model_year    188533 non-null  int64
 4   milage        188533 non-null  int64
 5   fuel_type     183450 non-null  object
 6   engine        188533 non-null  object
 7   transmission  188533 non-null  object
 8   ext_col       188533 non-null  object
 9   int_col       188533 non-null  object
 10  accident      186081 non-null  object
 11  clean_title   167114 non-null  object
 12  price         188533 non-null  int64
dtypes: int64(4), object(9)
memory usage: 18.7+ MB
None

=====================Test======================

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125690 entries, 0 to 125689
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            125690 non-null  int64
 1   brand         125690 non-null  object
 2   model         125690 non-null  object
 3   model_year    125690 non-null  int64
 4   milage        125690 non-null  int64
 5   fuel_type     122307 non-null  object
 6   engine        125690 non-null  object
 7   transmission  125690 non-null  object
 8   ext_col       125690 non-null  object
 9   int_col       125690 non-null  object
 10  accident      124058 non-null  object
 11  clean_title   111451 non-null  object
dtypes: int64(3), object(9)
memory usage: 11.5+ MB
None

In [75]:
print(f"Duplicati:\n - Train: {df_train.duplicated().sum()}\n - Test: {df_test.duplicated().sum()}")

Duplicati:
 - Train: 0
 - Test: 0

In [76]:
import numpy as np

In [77]:
df_train = df_train.drop(columns=['id','int_col'], axis=1)
df_train

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,accident,clean_title,price
0,MINI,Cooper S Base,2007,213000,Gasoline,172.0HP 1.6L 4 Cylinder Engine Gasoline Fuel,A/T,Yellow,None reported,Yes,4200
1,Lincoln,LS V8,2002,143250,Gasoline,252.0HP 3.9L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,At least 1 accident or damage reported,Yes,4999
2,Chevrolet,Silverado 2500 LT,2002,136731,E85 Flex Fuel,320.0HP 5.3L 8 Cylinder Engine Flex Fuel Capab...,A/T,Blue,None reported,Yes,13900
3,Genesis,G90 5.0 Ultimate,2017,19500,Gasoline,420.0HP 5.0L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,Black,None reported,Yes,45000
4,Mercedes-Benz,Metris Base,2021,7388,Gasoline,208.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,None reported,Yes,97500
...,...,...,...,...,...,...,...,...,...,...,...
188528,Cadillac,Escalade ESV Platinum,2017,49000,Gasoline,420.0HP 6.2L 8 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,None reported,Yes,27500
188529,Mercedes-Benz,AMG C 43 AMG C 43 4MATIC,2018,28600,Gasoline,385.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,8-Speed A/T,White,At least 1 accident or damage reported,Yes,30000
188530,Mercedes-Benz,AMG GLC 63 Base 4MATIC,2021,13650,Gasoline,469.0HP 4.0L 8 Cylinder Engine Gasoline Fuel,7-Speed A/T,White,None reported,Yes,86900
188531,Audi,S5 3.0T Prestige,2022,13895,Gasoline,3.0L,1-Speed Automatic,Daytona Gray Pearl Effect,None reported,NaN,84900
188532,Porsche,Macan Base,2016,59500,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,Transmission w/Dual Shift Mode,White,None reported,Yes,28995

In [78]:
df_test = df_test.drop(columns=['id','int_col'], axis=1)
df_test

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,accident,clean_title
0,Land,Rover LR2 Base,2015,98000,Gasoline,240.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,6-Speed A/T,White,None reported,Yes
1,Land,Rover Defender SE,2020,9142,Hybrid,395.0HP 3.0L Straight 6 Cylinder Engine Gasoli...,8-Speed A/T,Silver,None reported,Yes
2,Ford,Expedition Limited,2022,28121,Gasoline,3.5L V6 24V PDI DOHC Twin Turbo,10-Speed Automatic,White,None reported,NaN
3,Audi,A6 2.0T Sport,2016,61258,Gasoline,2.0 Liter TFSI,Automatic,Silician Yellow,None reported,NaN
4,Audi,A6 2.0T Premium Plus,2018,59000,Gasoline,252.0HP 2.0L 4 Cylinder Engine Gasoline Fuel,A/T,Gray,None reported,Yes
...,...,...,...,...,...,...,...,...,...,...
125685,Mercedes-Benz,GL-Class GL 450 4MATIC,2014,83315,Gasoline,362.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,7-Speed A/T,Black,None reported,Yes
125686,Audi,Q7 55 Prestige,2019,29336,Gasoline,3.0 Liter Turbo,Automatic,White,None reported,NaN
125687,Audi,A6 3.0T Premium Plus,2012,77634,Gasoline,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,Black,None reported,Yes
125688,Audi,Q7 3.0T Premium,2012,112000,Gasoline,333.0HP 3.0L V6 Cylinder Engine Gasoline Fuel,A/T,Black,None reported,Yes
125689,Chevrolet,Tahoe LT,2018,66840,Gasoline,355.0HP 5.3L 8 Cylinder Engine Gasoline Fuel,A/T,Silver,None reported,Yes

In [79]:
df_train["fuel_type"].unique()

array(['Gasoline', 'E85 Flex Fuel', nan, 'Hybrid', 'Diesel',
       'Plug-In Hybrid', '–', 'not supported'], dtype=object)

In [80]:
df_train.isnull().sum()

brand               0
model               0
model_year          0
milage              0
fuel_type        5083
engine              0
transmission        0
ext_col             0
accident         2452
clean_title     21419
price               0
dtype: int64

In [81]:
df_test.isnull().sum()

brand               0
model               0
model_year          0
milage              0
fuel_type        3383
engine              0
transmission        0
ext_col             0
accident         1632
clean_title     14239
dtype: int64

In [82]:
from sklearn.impute import SimpleImputer
from sklearn.calibration import LabelEncoder

In [83]:
def process_engine(df):
    if 'engine' in df.columns:
        df['horsepower'] = df['engine'].str.extract(r'(\d+\.\d+)(?=HP)').astype(float)
        df['engine_size'] = df['engine'].str.extract(r'(\d+\.\d+)(?=L)').astype(float)
        df['cylinders'] = df['engine'].str.extract(r'(\d+)\s(?:Cylinder|V\d|Straight)')[0].astype(float)

        df['horsepower'] = round(df['horsepower'].fillna(df['horsepower'].mean()))
        df['engine_size'] = round(df['engine_size'].fillna(df['engine_size'].mean()))
        df['cylinders'] = round(df['cylinders'].fillna(df['cylinders'].mean()))
        
        df = df.drop('engine', axis=1)
    return df

def clean_transmission(value):
    if pd.isna(value): return 'Other'
    val = value.lower()
    if 'cvt' in val: return 'CVT'
    elif 'manual' in val or 'm/t' in val: return 'Manual'
    elif 'auto-shift' in val or 'dct' in val or 'dual shift' in val: return 'Dual-Clutch'
    elif 'a/t' in val or 'automatic' in val or 'overdrive' in val: return 'Automatic'
    elif 'speed' in val and ('mt' in val or 'm/t' in val): return 'Manual'
    else: return 'Other'

def process_transmission(df):
    if 'transmission' in df.columns:
        df['transmission'] = df['transmission'].apply(clean_transmission)
    return df

def preprocess_data(df):
    # Drop colonne inutili
    df = df.drop(columns=['int_col'], errors='ignore')

    # Pulizia fuel_type
    df['fuel_type'] = df['fuel_type'].replace(['–', 'not supported'], np.nan)
    df['fuel_type'] = df['fuel_type'].fillna(df['fuel_type'].mode()[0])

    # Pulizia accident e clean_title
    df['accident'] = df['accident'].fillna('None reported')
    df['clean_title'] = df['clean_title'].fillna('No')

    # Applicazione funzioni modulari
    df = process_engine(df)
    df = process_transmission(df)

    # Label encoding per model e brand
    for col in ['model', 'brand']:
        if col in df.columns:
            le = LabelEncoder()
            df[col] = le.fit_transform(df[col].astype(str))

    # One-Hot Encoding su colonne categoriche
    categorical_cols = ['fuel_type', 'transmission', 'ext_col', 'accident', 'clean_title']
    existing_cols = [col for col in categorical_cols if col in df.columns]
    encoder = OneHotEncoder(drop='first', handle_unknown='ignore')
    encoded_data = encoder.fit_transform(df[existing_cols]).toarray()
    cols = encoder.get_feature_names_out(existing_cols)
    print(cols.shape)
    encoded_df = pd.DataFrame(encoded_data, columns=cols, index=df.index)

    non_categorical_cols = df.drop(columns=existing_cols)
    df = pd.concat([non_categorical_cols, encoded_df], axis=1)

    return df

In [84]:
df_train = preprocess_data(df_train)
df_train.head()

(328,)

,brand,model,model_year,milage,price,horsepower,engine_size,cylinders,fuel_type_E85 Flex Fuel,fuel_type_Gasoline,...,ext_col_Wolf Gray,ext_col_Yellow,ext_col_Yulong,ext_col_Yulong White,ext_col_designo Diamond White,ext_col_designo Diamond White Bright,ext_col_designo Diamond White Metallic,ext_col_–,accident_None reported,clean_title_Yes
0,31,495,2007,213000,4200,172.0,2.0,4.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1,28,930,2002,143250,4999,252.0,4.0,8.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,9,1575,2002,136731,13900,320.0,5.0,8.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
3,16,758,2017,19500,45000,420.0,5.0,8.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
4,36,1077,2021,7388,97500,208.0,2.0,4.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0

In [85]:
df_train.isnull().sum()

brand                                     0
model                                     0
model_year                                0
milage                                    0
price                                     0
                                         ..
ext_col_designo Diamond White Bright      0
ext_col_designo Diamond White Metallic    0
ext_col_–                                 0
accident_None reported                    0
clean_title_Yes                           0
Length: 336, dtype: int64

In [86]:
df_test.isnull().sum()

brand               0
model               0
model_year          0
milage              0
fuel_type        3383
engine              0
transmission        0
ext_col             0
accident         1632
clean_title     14239
dtype: int64

In [87]:
df_test['fuel_type'].unique()

array(['Gasoline', 'Hybrid', 'Diesel', 'E85 Flex Fuel', nan,
       'Plug-In Hybrid', '–', 'not supported'], dtype=object)

In [88]:
df_test['accident'].unique()

array(['None reported', 'At least 1 accident or damage reported', nan],
      dtype=object)

In [89]:
df_train['brand'].unique()

array([31, 28,  9, 16, 36,  3, 14,  4, 52,  8, 26, 15, 53, 19, 55, 54,  7,
       45, 44, 18,  1, 20, 22, 43, 35, 17, 27, 11, 39, 21,  0, 24, 38, 46,
       32, 42, 48,  5, 34, 50, 13,  2, 25, 10, 30, 29, 49, 56, 23, 40, 51,
       12, 47,  6, 37, 41, 33])

In [90]:
df_train['model'].unique()

array([ 495,  930, 1575, ..., 1885,  906,  882], shape=(1897,))

In [ ]:

import pandas as pd

df_encoded = df_train.copy()

categorical_cols = ['brand', 'fuel_type', 'transmission', 'ext_col', 'int_col', 'accident', 'clean_title']

df_encoded = pd.get_dummies(df_encoded, columns=categorical_cols, drop_first=True) # drop_first=True per evitare multicollinearità

KeyError: "['fuel_type', 'transmission', 'ext_col', 'int_col', 'accident', 'clean_title'] not in index"